[package]
name = "fermat"
version = "0.1.0"
authors = ["Hisayuki Mima <youxkei@gmail.com>"]
edition = "2018"

[dependencies]
tree-sitter = "0.17.1"
itertools = "0.9.0"
rpds = "0.7.0"

[build-dependencies]
cc = "1.0"

[dev-dependencies]
insta = "0.16.1"
